FROM confluentinc/cp-kafka-connect-base:7.7.7

COPY confluentinc-kafka-connect-elasticsearch-15.1.2 /usr/share/confluent-hub-components/confluentinc-kafka-connect-elasticsearch-15.1.2

ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components"